### ISSUE TITLE
Main package.json contains "seed" script that references non-existent file.

### ISSUE THREAD

**Issue by schapm16** [amesmr/js-flashcards#43]
#### Issue
The main [package.json](https://github.com/amesmr/js-flashcards/blob/master/package.json) contains a "seed" script that runs commands on a file that doesn't exist anymore.

#### Question
What is the preferred method for seeding a local MongoDB with Checkpoint data?

**Comment by dbdoyle182** [comment]
Nice catch! That was some old code, I'm working at replacing that now!

**Comment by dbdoyle182** [comment]
Take a peek now, if it works for you we can go ahead and close this issue.

**Comment by schapm16** [comment]
It works.  Thanks.
