### ISSUE TITLE
Wireframe home/landing page 

### ISSUE THREAD

**Issue by dbdoyle182** [amesmr/js-flashcards#6]
What is the page structure on page load? Is there a list of the various topics which then leads to the flashcards? Or is there a top nav bar that allows the user to filter based on topic, checkpoint number, all questions up till where they are in the course, etc. I'm open to anything!

**Comment by mfbradley** [comment]
I like the idea of a list of topics that lead to flashcards

**Comment by mfbradley** [comment]
Maybe we could also add the option to click on multiple topics, allowing the user to combine several into one deck of flashcards.
